### ISSUE TITLE
acf-json folder

### ISSUE THREAD

**Issue by damien-pilot-in** [Pilot-in/PiloPress-Starter-Theme#6]
Should we add `acf-json` folder by default?

**Comment by michael-dev-pilotin** [comment]
There is a bug where fields group json are not sync properly without this folder.
Create it ASAP 😄

**Comment by Pilotin** [comment]
Pilo'Press should work correctly without it, even if we can create it by default in the starter theme. We should fix the problem first tho.

**Comment by maelys-pilotin** [comment]
Folder added.
JSON sync issue is Pilo'Press Plugin territory, please add an issue in this repository with more details !
